require('express')
require('body-parser')
require('./controllers/login')
require('./register/register')
require('./controllers/forgotpassword')
require('./config/passport')(require('passport'))
require('./role/roleController')
require('./controllers/section')
require('./checkin/checkinController')
require('./users/userController')
require('./treasureHunt/model')

require('./config/database')
  .sync()
  .then(() => {
    process.exit()
  })
